# A miniature of the one place. It is HONEST about the tree, so what this tree
# demonstrates is the component-side cases rather than the mechanism.
#
# It emits all five fields, and it has to: the gate holds whatever it finds at
# this path to the value contract by RUNNING it, so a miniature that emitted
# three fields would fail this tree for the mechanism's shape on top of the three
# component-side cases it exists to demonstrate. A fixture that also fails for
# something it is not about is a fixture whose declared cases stop being
# readable.

STAMP_SRC       ?= .
STAMP_COMPONENT ?= demo
STAMP_OUT       ?= cmd/demo/build_stamp.go

.PHONY: stamp

stamp:
	@commit=$$(git -C '$(STAMP_SRC)' rev-parse HEAD 2>/dev/null || echo unknown); \
	version=$$(git -C '$(STAMP_SRC)' describe --tags 2>/dev/null || echo untagged); \
	if [ -n "$$(git --no-optional-locks -C '$(STAMP_SRC)' status --porcelain 2>/dev/null)" ]; \
	  then tree=dirty; else tree=clean; fi; \
	built_at=$$(date -u +%Y-%m-%dT%H:%M:%SZ); \
	mkdir -p "$$(dirname '$(STAMP_OUT)')"; \
	echo '// Code generated by `make stamp`. DO NOT EDIT.' > '$(STAMP_OUT)'; \
	echo "stamp: component=$(STAMP_COMPONENT) version=$$version commit=$$commit tree=$$tree built_at=$$built_at"
