// Command telephone is the sidecar: the program a tenant runs beside their own
// backend. It dials out to the proxy, so the tenant needs no inbound network
// path and no listening port.
//
// Skeleton only. What it will own is stated once, in
// docs/code/boundaries/sidecar.md, and its behaviour is owned by the
// sidecar/program specification. Neither is restated here.
//
// It does report one thing already: the build it is, on the second line it
// writes. startupReport and the stamp it renders are generated by `make stamp`
// into build_stamp.go, from the one place that stamps every component
// (ci/make/go.mk) -- so this file cannot compile without a stamp and cannot hold
// a second opinion about one.
package main

import (
	"fmt"
	"os"

	"plugboard/sidecar/internal/tunnel"
)

func main() {
	if _, err := fmt.Fprintln(os.Stdout, startupReport(tunnel.Banner())); err != nil {
		os.Exit(1)
	}
}
