// Code generated by `make stamp` (ci/make/go.mk). DO NOT EDIT.

package main

import "strings"

// buildStampOrder is the order the provenance fields are reported in.
var buildStampOrder = []string{"component", "version", "commit", "tree", "built_at"}

// buildStamp carries the provenance of this build, by field name.
var buildStamp = map[string]string{
	"component": "conformance",
	"version":   "untagged",
	"commit":    "059b35757ba4c3ed491a07d52d14aa26be8b2b1b",
	"tree":      "dirty",
	"built_at":  "2026-09-13T14:36:11Z",
}

// startupReport is what this component says about itself at startup: the
// banner, then its build provenance. It is the seam the per-component test
// asserts against, and the only renderer of the stamp.
func startupReport(banner string) string {
	parts := make([]string, 0, len(buildStampOrder))
	for _, name := range buildStampOrder {
		parts = append(parts, name+"="+buildStamp[name])
	}
	return banner + "\nbuild-provenance " + strings.Join(parts, " ")
}
