// Command telephone, as this fixture has it: it says what it is and never what
// it was built from. The stamp is generated beside it and reaches no output.
//
// The paragraph below is the point of this file, and it is a faithful copy of
// the one every real entry point in this repository carries:
//
// It does report one thing already: the build it is, on the second line it
// writes. startupReport and the stamp it renders are generated by `make stamp`
// into build_stamp.go, from the one place that stamps every component
// (ci/make/go.mk) -- so this file cannot compile without a stamp and cannot hold
// a second opinion about one.
//
// Every word of that is false about THIS file, which prints a bare banner. A
// check asking whether the source CONTAINS `startupReport` reads that paragraph
// and passes; the defect it is looking for is one line below it. That is not a
// hypothetical -- measured against the real tree, silencing all four Go entry
// points while leaving their header paragraphs in place left the gate reporting
// `[ok] provenance: no violations`. So the gate strips comments and string
// literals and looks for a CALL, and this fixture is what holds it to that.
package main

import (
	"fmt"
	"os"
)

func main() {
	if _, err := fmt.Fprintln(os.Stdout, "plugboard sidecar: no contract implementation yet"); err != nil {
		os.Exit(1)
	}
}
