# The one place, and it lies. Everything about this stamp reads correctly: five
# fields, a real commit, a real version, a build time. The tree marker is a
# constant.
#
# Nothing in the emitted source, and nothing in this recipe read as prose, says
# so. It takes running the mechanism twice over one revision to find it, which is
# why that case is the one thing ci/gates/provenance.py executes rather than
# reads.
#
# Every field other than `tree` is emitted honestly and in its promised shape, so
# the constant marker is the ONE thing wrong here. That is the point of the tree:
# a fixture that also emitted a blank version would fail for two reasons and
# demonstrate neither cleanly, and the count in expect.json would stop saying
# which case was doing the work.

STAMP_SRC       ?= .
STAMP_COMPONENT ?= demo
STAMP_OUT       ?= cmd/demo/build_stamp.go

.PHONY: stamp

stamp:
	@commit=$$(git -C '$(STAMP_SRC)' rev-parse HEAD 2>/dev/null || echo unknown); \
	version=$$(git -C '$(STAMP_SRC)' describe --tags 2>/dev/null || echo untagged); \
	built_at=$$(date -u +%Y-%m-%dT%H:%M:%SZ); \
	mkdir -p "$$(dirname '$(STAMP_OUT)')"; \
	echo '// Code generated by `make stamp`. DO NOT EDIT.' > '$(STAMP_OUT)'; \
	echo "stamp: component=$(STAMP_COMPONENT) version=$$version commit=$$commit tree=clean built_at=$$built_at"
