defmodule Plugboard.Application do
  @moduledoc """
  The proxy's OTP entry point. It supervises nothing yet — no tunnel, no
  listener, no registry — and exists now for one reason: startup is where a
  component says what it was built from, and there was no startup.

  The stamp it reports is generated by `make stamp` into
  `lib/plugboard/build_stamp.ex` from the one place that stamps every component,
  `ci/make/go.mk`. Nothing here computes a version, a commit or a build time,
  and nothing here may: a second copy is how one component learns to report a
  dirty tree while another never does.
  """
  use Application

  require Logger

  @impl Application
  @spec start(Application.start_type(), term()) :: {:ok, pid()} | {:error, term()}
  def start(_type, _args) do
    :ok = report_provenance()
    Supervisor.start_link([], strategy: :one_for_one, name: Plugboard.Supervisor)
  end

  @doc """
  Emits the build provenance, and is the same call `start/2` makes.

  It is a named function rather than a line inside `start/2` so that a test can
  assert what is reported without starting a supervision tree — an emission no
  test reads is the shape this repository keeps finding under other names.
  """
  @spec report_provenance() :: :ok
  def report_provenance do
    Logger.info(Plugboard.BuildStamp.line())
  end
end
