#!/usr/bin/env python3
"""The one place build provenance is computed. rebuild-plugboard task 3.13.

Four values -- version, commit, dirty-tree marker, build time -- derived here and
written into one generated source per component. ONE PLACE is the whole point: a
component that computed its own would drift from the others, and the drift would
be invisible because each would look self-consistent.

The generated file is a BUILD ARTIFACT and is gitignored. It is not a tracked
generated file and deliberately not a ci/gen/ tool: ci/gates/generators.py holds
every tool there to a pinned expected output, and a stamp containing a build time
cannot have one. Saying that plainly matters -- the alternative is a tool declared
under an oracle it can never satisfy, which is worse than no oracle.

Usage:
    python3 ci/stamp.py --component sidecar --language go    > path/to/stamp.go
    python3 ci/stamp.py --component proxy   --language elixir > path/to/stamp.ex
    python3 ci/stamp.py --values                              # JSON, for a test
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

#: The declared field set. ci/gates/provenance.py reads it from here, so the gate
#: and the generator cannot disagree about what provenance IS.
FIELDS = ("version", "commit", "tree", "built_at")

#: What the dirty-tree marker says. Two words, not a boolean, because a boolean
#: printed at startup reads as noise and a word reads as a fact. UNKNOWN is the
#: third: git not answering is not the same fact as a clean tree, and reporting
#: the affirmative word for it is a claim nothing checked.
CLEAN, DIRTY, UNKNOWN = "clean", "dirty", "unknown"


def _git(*args: str) -> str | None:
    """Trimmed stdout, or None when git did not answer.

    None rather than "" because the two are different facts and one caller cares:
    `git status --porcelain` returns EMPTY for a clean tree and FAILS where there
    is no repository, and collapsing those reported a modified tree built outside
    a checkout as `clean`.
    """
    try:
        return subprocess.run(
            ["git", *args],
            capture_output=True,
            text=True,
            check=True,
            cwd=str(Path(__file__).resolve().parent.parent),
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def values(built_at: str | None = None) -> dict[str, str]:
    describe = _git("describe", "--tags", "--always", "--dirty")
    porcelain = _git("status", "--porcelain")
    return {
        "version": describe or UNKNOWN,
        "commit": _git("rev-parse", "HEAD") or UNKNOWN,
        # The marker is derived from the WORKING TREE, not from the version
        # string: `git describe --dirty` appends a suffix only when tags exist,
        # so a repository with no tags would report every build clean.
        "tree": UNKNOWN if porcelain is None else (DIRTY if porcelain else CLEAN),
        "built_at": built_at or _git("log", "-1", "--format=%cI") or UNKNOWN,
    }


def escape(value: str, language: str) -> str:
    """A derived value made safe to sit inside a source literal.

    These values come from REFS -- a tag or branch name someone else may have
    written -- and they are interpolated into source that is then compiled. That
    is an injection site, and it was one:

      * Elixir evaluates `#{...}` inside a double-quoted string AT COMPILE TIME.
        A tag named `v1-#{File.read!("/etc/passwd")}` on any ancestor commit ran
        arbitrary code in every later build.
      * Go has no interpolation, but a `"` in a tag closed the literal and emitted
        source that does not compile.

    Escaping rather than sanitising: a stamp that silently rewrites the version it
    reports is a stamp that lies, which is the one thing it exists not to do.
    """
    out = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    if language == "elixir":
        out = out.replace("#", "\\#")
    return out


GO = """// Code generated by ci/stamp.py. DO NOT EDIT.
// A build artifact: gitignored, regenerated by `make stamp`, and never committed.
package buildstamp

import "fmt"

// Stamp is this artifact's provenance, fixed at build time from one place.
//
// A struct rather than a map[string]string. The field set is known, closed and
// four items long, and this repository treats a map where a shape belongs as the
// canary for a whole defect class -- see docs/code/banned-patterns/headers-as-a-map.md.
// The reason there is about header fields, but the habit is the thing.
type Stamp struct {{
	Version  string
	Commit   string
	Tree     string
	BuiltAt  string
}}

// Build is the provenance of this binary.
var Build = Stamp{{
{entries}
}}

// Component is the deployable this binary is.
const Component = "{component}"

// Line is what this component reports at startup: its identity and the four
// provenance fields.
//
// It lives here, generated, rather than in each component's main. Three mains
// carried an identical copy of it and `code-duplication` refused them -- rightly:
// Go cannot share a package across modules, so the copies would have drifted in
// format the first time one of them was edited, and a provenance line whose SHAPE
// differs per component is one no operator can compare across a pair.
func Line() string {{
	return fmt.Sprintf("%s version=%s commit=%s tree=%s built=%s",
		Component, Build.Version, Build.Commit, Build.Tree, Build.BuiltAt)
}}
"""

EX = """# Code generated by ci/stamp.py. DO NOT EDIT.
# A build artifact: gitignored, regenerated by `make stamp`, and never committed.
defmodule Plugboard.BuildStamp do
  @moduledoc "This artifact's provenance, fixed at build time from one place."

  @stamp %{{
{entries}
  }}

  @component "{component}"

  @doc "The provenance map."
  @spec stamp() :: %{{String.t() => String.t()}}
  def stamp, do: @stamp

  @doc "The deployable this release is."
  @spec component() :: String.t()
  def component, do: @component
end
"""


def render(component: str, language: str, vals: dict[str, str]) -> str:
    if language == "go":
        return _gofmt(_render_go(component, vals))
    # Joined with the separator rather than suffixed: a trailing comma on the
    # last pair is what `mix format --check-formatted` refuses, and it refused it
    # in CI on a file no human wrote. The Go side is piped through gofmt for the
    # same reason; Elixir's formatter is not reachable from here (mix needs a
    # project context and may be absent), so the one thing it cares about is not
    # emitted in the first place.
    entries = ",\n".join(
        f'    "{k}" => "{escape(v, "elixir")}"' for k, v in vals.items()
    )
    return EX.format(entries=entries, component=escape(component, "elixir"))


def _gofmt(source: str) -> str:
    """Run the emitted Go through gofmt.

    The generated file is gitignored but it is still COMPILED and LINTED, and
    golangci-lint runs gofmt as a formatter -- so a generator that emits
    misaligned struct literals makes `make lint` fail on a file no human wrote.
    Hand-aligning the template instead would put a second formatter in this file,
    one that drifts from the real one the first time a field name changes length.
    """
    try:
        done = subprocess.run(["gofmt"], input=source, capture_output=True, text=True)
    except FileNotFoundError:
        # gofmt absent is an environment gap, not a defect in the output. Say so
        # on stderr rather than silently emitting source the linter will refuse.
        print(
            "ci/stamp.py: gofmt is not on PATH; emitting unformatted Go",
            file=sys.stderr,
        )
        return source
    if done.returncode != 0:
        # gofmt refusing is gofmt REPORTING A SYNTAX ERROR in what this generator
        # just produced. Swallowing it emitted broken Go and exited 0, so the
        # first sign was a compile failure with no mention of the generator.
        raise SystemExit(
            f"ci/stamp.py: gofmt refused the generated source, which means this "
            f"generator emitted Go that does not parse:\n{done.stderr.strip()}"
        )
    return done.stdout


def _render_go(component: str, vals: dict[str, str]) -> str:
    names = {
        "version": "Version",
        "commit": "Commit",
        "tree": "Tree",
        "built_at": "BuiltAt",
    }
    entries = "\n".join(f'\t{names[k]}: "{escape(v, "go")}",' for k, v in vals.items())
    return GO.format(entries=entries, component=escape(component, "go"))


def main(argv: list[str]) -> int:
    description = __doc__ or "Generate a build-provenance stamp"
    ap = argparse.ArgumentParser(description=description.splitlines()[0])
    ap.add_argument("--component")
    ap.add_argument("--language", choices=("go", "elixir"))
    ap.add_argument(
        "--values",
        action="store_true",
        help="print the four values as JSON and write no source",
    )
    args = ap.parse_args(argv)
    if args.values:
        print(json.dumps(values(), indent=2))
        return 0
    if not args.component or not args.language:
        ap.error("--component and --language are required unless --values is given")
    sys.stdout.write(render(args.component, args.language, values()))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
